/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Momo.glb --shadows -o model3.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Momo.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Chin" geometry={nodes.Chin.geometry} material={materials.eyebrows} skeleton={nodes.Chin.skeleton} />
          <skinnedMesh name="Eye1" geometry={nodes.Eye1.geometry} material={nodes.Eye1.material} skeleton={nodes.Eye1.skeleton} />
          <skinnedMesh name="Eye2" geometry={nodes.Eye2.geometry} material={nodes.Eye2.material} skeleton={nodes.Eye2.skeleton} />
          <skinnedMesh name="Eyebrow1" geometry={nodes.Eyebrow1.geometry} material={materials['eyebrows.001']} skeleton={nodes.Eyebrow1.skeleton} />
          <skinnedMesh name="Eyebrow2" geometry={nodes.Eyebrow2.geometry} material={materials.eyebrows} skeleton={nodes.Eyebrow2.skeleton} />
          <skinnedMesh name="Hair" geometry={nodes.Hair.geometry} material={materials.eyebrows} skeleton={nodes.Hair.skeleton} />
          <skinnedMesh name="Hairbase" geometry={nodes.Hairbase.geometry} material={materials.eyebrows} skeleton={nodes.Hairbase.skeleton} />
          <group name="Mustache">
            <skinnedMesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials.eyebrows} skeleton={nodes.Mesh004.skeleton} />
            <points name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials.eyebrows} />
          </group>
          <skinnedMesh name="Pants" geometry={nodes.Pants.geometry} material={materials['Pants Color']} skeleton={nodes.Pants.skeleton} />
          <skinnedMesh name="Pupil1" geometry={nodes.Pupil1.geometry} material={materials.pupil} skeleton={nodes.Pupil1.skeleton} />
          <skinnedMesh name="Pupil2" geometry={nodes.Pupil2.geometry} material={materials.pupil} skeleton={nodes.Pupil2.skeleton} />
          <skinnedMesh name="Pupil2001" geometry={nodes.Pupil2001.geometry} material={materials['Material.001']} skeleton={nodes.Pupil2001.skeleton} />
          <skinnedMesh name="Pupil2002" geometry={nodes.Pupil2002.geometry} material={materials['Material.001']} skeleton={nodes.Pupil2002.skeleton} />
          <skinnedMesh name="Pupil2003" geometry={nodes.Pupil2003.geometry} material={materials['Material.001']} skeleton={nodes.Pupil2003.skeleton} />
          <skinnedMesh name="Pupil2004" geometry={nodes.Pupil2004.geometry} material={materials['Material.001']} skeleton={nodes.Pupil2004.skeleton} />
          <group name="Retopology">
            <skinnedMesh name="Plane" geometry={nodes.Plane.geometry} material={materials.SKIN} skeleton={nodes.Plane.skeleton} />
            <points name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.SKIN} />
          </group>
          <skinnedMesh name="Shirt" geometry={nodes.Shirt.geometry} material={materials['Material.001']} skeleton={nodes.Shirt.skeleton} />
          <skinnedMesh name="Shoes" geometry={nodes.Shoes.geometry} material={materials['Material.002']} skeleton={nodes.Shoes.skeleton} />
          <skinnedMesh name="TeethBottom" geometry={nodes.TeethBottom.geometry} material={nodes.TeethBottom.material} skeleton={nodes.TeethBottom.skeleton} />
          <skinnedMesh name="TeethTop" geometry={nodes.TeethTop.geometry} material={nodes.TeethTop.material} skeleton={nodes.TeethTop.skeleton} />
          <skinnedMesh name="Veste" geometry={nodes.Veste.geometry} material={materials.Vest} skeleton={nodes.Veste.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Momo.glb')
